### ISSUE TITLE
Remove PHPStorm config files from Git

### ISSUE THREAD

**Issue by davidromani** [aserratorta/SymfonyTraining#1]
Read this comment: https://github.com/aserratorta/Symfony-Training/commit/be42a292f5ac1242d5fcc4a6cae7bbbe2455db79

Hint about how to remove tracked files: http://www.gitguys.com/how-to-remove-a-file-from-git-source-control-but-not-delete-it/

**Comment by aserratorta** [comment]
I'm trying to remove these files through my useful git bash, but i can't. It doesn't allow me put inside /Symfony Training folder and order git rm --cached file

**Comment by davidromani** [comment]
Show me the bash error message

**Comment by aserratorta** [comment]
This is my browser structure where Symfony Training folder is in.

![image](https://cloud.githubusercontent.com/assets/12971681/8686382/1c444874-2a86-11e5-92fd-951e1ebde02e.png)

When I try to do this, I can't.

Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

Anton@SERRAMESTRE ~ (master)
$ cd Symfony Training

Anton@SERRAMESTRE ~/Symfony (master)
$ ls -la
total 109
drwxr-xr-x   12 Anton    Administ     4096 Jul  8 19:00 .
drwxr-xr-x    1 Anton    Administ    12288 Jul 11 22:34 ..
drwxr-xr-x   14 Anton    Administ     4096 Jul 13 22:32 .git
-rw-r--r--    1 Anton    Administ      879 Jul  8 19:00 .gitignore
-rw-r--r--    1 Anton    Administ      582 Jul  8 19:00 .travis.yml
-rw-r--r--    1 Anton    Administ      485 Jul  8 19:00 README.md
drwxr-xr-x   16 Anton    Administ     4096 Jul  8 19:00 app
-rw-r--r--    1 Anton    Administ     3911 Jul  8 19:00 composer.json
-rw-r--r--    1 Anton    Administ   185704 Jul  8 19:00 composer.lock
drwxr-xr-x    4 Anton    Administ        0 Jul  8 19:00 src
-rwxr-xr-x    1 Anton    Administ      450 Jul  8 19:00 test.sh
drwxr-xr-x    9 Anton    Administ     4096 Jul  8 19:00 web

Anton@SERRAMESTRE ~/Symfony (master)
$ cd SymfonyTraining
sh.exe": cd: SymfonyTraining: No such file or directory

Anton@SERRAMESTRE ~/Symfony (master)
$ cd Symfony-Training
sh.exe": cd: Symfony-Training: No such file or directory

Anton@SERRAMESTRE ~/Symfony (master)
$ cd PhpstormProjects
sh.exe": cd: PhpstormProjects: No such file or directory

**Comment by davidromani** [comment]
The problem is due to your change directory (cd) command. You have a blank space between "Symfony" & "Training" and you need to escape this character. If you think like a machine, the space speration means another thing (another argument or command parameter).

Hint: https://en.wikipedia.org/wiki/Path_(computing)#MS-DOS.2FMicrosoft_Windows_style
