### ISSUE TITLE
PhpStorm fine tuning

### ISSUE THREAD

**Issue by davidromani** [aserratorta/SymfonyTraining#10]
Follow this steps:
https://confluence.jetbrains.com/display/PhpStorm/Getting+Started+-+Symfony+Development+using+PhpStorm

**Comment by aserratorta** [comment]
I didn't understand if I must have changed the "Path to urlGenerator.php"
![screenshot - 180815 - 00 30 34](https://cloud.githubusercontent.com/assets/12971681/9318110/d387383c-4540-11e5-9ef2-b038db03287b.png)

**Comment by davidromani** [comment]
No, the plugin is working well in your case (default Symfony projects structure).
