### ISSUE TITLE
PhpStorm+Terminal

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#11]
Must I do it on this way in order to integrate the terminal in phpstorm?
![screenshot - 190815 - 16 43 10](https://cloud.githubusercontent.com/assets/12971681/9359545/e806b13c-4691-11e5-96f3-744043c4cbb3.png)

**Comment by davidromani** [comment]
Probably... yes. Read this http://www.kevwebdev.com/blog/setting-up-a-symfony2-project-in-phpstorm.html
