### ISSUE TITLE
Doctrine\ORM\Mapping\MappingException

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#12]
Hi David!
After creating a new entity, I try to order this command and it says me this:

![screenshot - 010915 - 02 36 39](https://cloud.githubusercontent.com/assets/12971681/9593712/64bd719c-5052-11e5-9b22-b59ef07f3c8c.png)

What do you think the problem is?

**Comment by davidromani** [comment]
First try to execute doctrine:mapping:info & doctrine:schema:validate commands before and show me the output. And remeber to push all of your changes before asking because now, I can't try your code.

Lastly, I recommend to use 'annotation' format instead of 'php'

**Comment by aserratorta** [comment]
You're right! I didn't remember to push last night :sweat_smile:
Here you are:
![screenshot - 010915 - 14 59 29](https://cloud.githubusercontent.com/assets/12971681/9605118/109edf46-50bc-11e5-808e-a4a91846770e.png)

**Comment by aserratorta** [comment]
What do you mean annotation? yaml, xml?

**Comment by davidromani** [comment]
Annotation is more "human-readable". Pull my commit and try to understand your mistakes. Look close at differences and ask me something.

**Comment by aserratorta** [comment]
Wile I was creating a new entity I saw the possibility to create it with annotation, so I understand what "annotation" is. These were all my problems with meta dates.:satisfied:

**Comment by davidromani** [comment]
Good lesson, well done.
