### ISSUE TITLE
Insert dates into a data base 8.1.7

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#13]
a5f4ad91d021fbe652aec0c631792f3dafcdddc7

Look at this commit, please. 
I inserted dates on defaultcontroller.php.
I wanted to show these dates on the productos.html.twig, but I'm not be able to do it.
The problem is the route, controllers,... Quite difficult to comprehend.

**Comment by davidromani** [comment]
Where? I'm looking at the default controller and I don't see dates anywhere.

First ol all, you need to declare a date attribute in your "Product" class, right?

**Comment by aserratorta** [comment]
I don't understand when you say _you need to declare a date attribute in your "Product" class_. 
Do you mean this one?:
**date: Type that maps a SQL DATETIME to a PHP DateTime object.**
Can you give me another hint, please? 
I thought I was inserting dates (new product) through DefaultController in order to the tutorial explained to me.

**Comment by aserratorta** [comment]
Hi David!
As you can see I keep trying to show my register in DefaultController onto the twig template (productos.html.twig.
d56111d
What am I doing wrong? I suppose a lot of things :sweat_smile:
I was searching in this website:
http://www.maestrosdelweb.com/curso-symfony2-manipulando-datos-con-doctrine/

**Comment by davidromani** [comment]
Basically, it's because you have renamed classes to english, but their file name still in spanish. This is a namespaces integrity violation.
