### ISSUE TITLE
Symfony\Component\HttpKernel\Exception\NotFoundHttpException

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#18]
Hi David!
This is the error profiler shows me:
![screenshot - 200915 - 00 18 00](https://cloud.githubusercontent.com/assets/12971681/9978423/d3094dda-5f2d-11e5-9503-917323119e9b.png)
And this is my latest commit with comments:
0e70aa1

**Comment by davidromani** [comment]
Check file src/TestBundle/Controller/DefaultController.php line 30.

If $offer doesn't exists, then it throws an exception (not found). So findOneBy method (line 25) from offers manager (repository) is returning **no** result when city=barcelona and publicationDate=today.

**Comment by davidromani** [comment]
Try to install this app http://dev.mysql.com/downloads/workbench/ is very helpful
