### ISSUE TITLE
mysql workbench

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#19]
Look at this David:
![screenshot - 230915 - 23 39 26](https://cloud.githubusercontent.com/assets/12971681/10059621/602fa47c-624c-11e5-8f88-89f9f163697e.png)

I don't know why it doesn't appear dates in my tables because I created some datafixtures and they're match with the entities...

**Comment by davidromani** [comment]
Probably you forget to execute Doctrine fixtures load command...

```
php app/console doctrine:fixtures:load 
```

**Comment by aserratorta** [comment]
Yes, you're right.
Now, I have to fix the entities :sweat_smile:
Do you think any idea in order to fix the last one runtime exception?
![screenshot - 240915 - 23 15 42](https://cloud.githubusercontent.com/assets/12971681/10087146/8f7d6518-6312-11e5-9c8d-be56ba4450ca.png)

**Comment by aserratorta** [comment]
Hi David,
I'm trying to load fixtures, but I must fix the code before.
The last red message appears is this one:

_[PDOException]  
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'slug' cannot be null_

Where do I have to go to fix it?

Thanks :wink:

**Comment by davidromani** [comment]
Pull this commit https://github.com/aserratorta/SymfonyTraining/commit/8e9af6a2984bb338a77ed5fe8b5d71856d19c6cd

**Comment by aserratorta** [comment]
Thanks!

**Comment by davidromani** [comment]
Did you understand why it has been fixed?

**Comment by aserratorta** [comment]
I think so.
I must have create slug method in all my entities, must not have?
Any way, I'll have to get use to the terminal's reports way.

**Comment by davidromani** [comment]
It depends on why do you really need a entity slug.

You need a slug when you must identify an entity unique value inside an URL. Slugs are useful to represent human-friendly URLs in a pretty way. For example:

```
http://www.mycoolweb.com/barcelona
http://www.mycoolweb.com/new-york
http://www.mycoolweb.com/salt-lake-city
```

In this case, probably you need a City class with a real name attribute, and his **not-null** slugified version because it's a bad practise to build URLs with blank spaces inside like:

```
"http://www.mycoolweb.com/New York"
"http://www.mycoolweb.com/Salt Lake City"
```

**Comment by aserratorta** [comment]
Understood :+1:
