### ISSUE TITLE
commiting from xubuntu terminal

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#2]
Hi David,
## The other day I tried to do git checkout devel and it said me:

anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ git checkout devel
error: Your local changes to the following files would be overwritten by checkout:
    .gitignore
    composer.json
    composer.lock
Please, commit your changes or stash them before you can switch branches.
error: Your local changes to the following files would be overwritten by checkout:
    .idea/Symfony Training.iml
    .idea/workspace.xml
Please, commit your changes or stash them before you can switch branches.
## Please, give a hint about what i have to do from here, because i'm not sure about it:

anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

```
new file:   .gitignore
new file:   README.md
new file:   app/.htaccess
new file:   app/AppCache.php
new file:   app/AppKernel.php
new file:   app/Resources/views/base.html.twig
new file:   app/Resources/views/default/index.html.twig
new file:   app/SymfonyRequirements.php
new file:   app/autoload.php
new file:   app/cache/.gitkeep
new file:   app/check.php
new file:   app/config/config.yml
new file:   app/config/config_dev.yml
new file:   app/config/config_prod.yml
new file:   app/config/config_test.yml
new file:   app/config/parameters.yml.dist
new file:   app/config/routing.yml
new file:   app/config/routing_dev.yml
new file:   app/config/security.yml
new file:   app/config/services.yml
new file:   app/console
new file:   app/logs/.gitkeep
new file:   app/phpunit.xml.dist
new file:   composer.json
new file:   composer.lock
new file:   src/.htaccess
new file:   src/AppBundle/AppBundle.php
new file:   src/AppBundle/Controller/DefaultController.php
new file:   src/AppBundle/Tests/Controller/DefaultControllerTest.php
new file:   web/.htaccess
new file:   web/app.php
new file:   web/app_dev.php
new file:   web/apple-touch-icon.png
new file:   web/config.php
new file:   web/favicon.ico
new file:   web/robots.txt
```

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
modified:   .idea/Symfony Training.iml
modified:   .idea/workspace.xml
```

---

Must I do commit from all the new files in branch master, first of all? I suppose yes... Verify me please.
After that, should I do git checkout devel? And then, should I do git pull?

Thank you and sorry!

**Comment by davidromani** [comment]
I suppose that the problem happens during migration to Linux environment. I think that it doesn't matter too much. Probably we were on master branch and we must jump to devel before to start migration.

.idea files can be ignored, so save changes on .gitignore and commit to master. Then you can jump to devel, and merge from master. At this point, you will have got merge conflicts with composer.json, composer.lock & .gitignore files.

Resolve it: check marks inside affected conflict files, remove devel fragments (the old ones), save, commit again (on devel branch), and push it.
