### ISSUE TITLE
Problems with fixtures Users.php

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#20]
Buff! More problems that I don't know how to solve :disappointed:

_[Symfony\Component\Debug\Exception\ContextErrorException]  
  Catchable Fatal Error: Argument 1 passed to TestBundle\DataFixtures\ORM\Users::getAddress() must be an instance of TestBundle\DataFixtures\ORM\City, instance of TestBundle  
  \Entity\City given, called in /home/anton/Desenvolupament/SymfonyTraining/src/TestBundle/DataFixtures/ORM/Users.php on line 49 and defined_

**Comment by davidromani** [comment]
A good example about namesapaces and class names collisions. You can use multiple classes with the same name, but be carreful to **use** the right one into use declarations section.

Any question?
