### ISSUE TITLE
it render nothing

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#21]
I don't know why it doesn't render anything.
Barcelona is the default city and it has 15 offers.

![screenshot - 031015 - 00 20 22](https://cloud.githubusercontent.com/assets/12971681/10259129/252b2a16-6965-11e5-82b1-2092927016ec.png)

**Comment by davidromani** [comment]
Check this commit https://github.com/aserratorta/SymfonyTraining/commit/3926aa9a9db963135a5a43407c5a1c6a26655df1 and remeber to load fixtures before to execute because this app needs a current offer reletad to a dynamic date (today)
