### ISSUE TITLE
app/console assets:install web

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#22]
I'm trying to render the stylesheets. When I install the assets it appears this message:
**Installing assets as hard copies.
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
Installing assets for TestBundle into web/bundles/test
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution**

Shouldn't it be **Installing assets for Symfony/Bundle/WebProfilerBundle into web/bundles/webprofiler**?
I don't get to render the stylesheets...:sweat:
![screenshot - 041015 - 01 08 03](https://cloud.githubusercontent.com/assets/12971681/10265535/64acd8ae-6a34-11e5-8084-826f55d3209e.png)

**Comment by davidromani** [comment]
Well, take care about which is the view that the controller is rendering...

```
<?php

namespace TestBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
(...)

class DefaultController extends Controller
{
    public function frontAction($city = null)
    {
      (...)
       return $this->render('TestBundle:Default:front.html.twig', array(
                'offer' => $offer,
                'currentCity' => $city,
            )
        );
    }
}
```

Slow down, and read carefully src/TestBundle/Resources/views/Default/front.html.twig view file. Have you noticed something strange or missing parts?

**Comment by aserratorta** [comment]
{% extends '::frontend.html.twig' %} :sweat_smile:

![screenshot - 041015 - 01 08 03](https://cloud.githubusercontent.com/assets/12971681/10270650/c86c321c-6af8-11e5-8e1d-f1ccfad2f26e.png)

**Comment by davidromani** [comment]
Nice view, congratulations! :+1:
