### ISSUE TITLE
Pulling 

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#4]
Hi David, 

when you can I'd like to talk to you about this 2 options about after fetching changes:
![screenshot - 100815 - 00 44 52](https://cloud.githubusercontent.com/assets/12971681/9157306/0bfb9058-3ef9-11e5-9e00-e772429c6f8c.png)
I'll send you a msg.

**Comment by davidromani** [comment]
Ok. For now, you can use "Merge fetched remote changes" as a default behaviour. Rebase is easy to understand, but we don't need this feature at this moment.

**Comment by aserratorta** [comment]
Hi!
I pull as you said. Then I do git commit on devel, but there aren't any merge conflicts.

---

anton@anton-System-Name:~$ cd /home/anton/Desenvolupament/SymfonyTraining/
anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ git status
On branch devel
Your branch is up-to-date with 'origin/devel'.

nothing to commit, working directory clean
anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ git branch
- devel
  master
  anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ git status
  On branch devel
  Your branch is up-to-date with 'origin/devel'.

nothing to commit, working directory clean
anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ 

---

Am I completely up-to-date?

**Comment by davidromani** [comment]
Everything seems ok
