### ISSUE TITLE
4.2.2. Paso 2: Creando el controlador

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#5]
David,
Aquest punt del tutorial em dona el següent error:
![screenshot - 140815 - 03 11 37](https://cloud.githubusercontent.com/assets/12971681/9265349/359e6124-4232-11e5-8622-acff884367ff.png)
No sé que estic fent malament...

**Comment by davidromani** [comment]
Very easy to resolve :smiley: 

Look very close to src/HelloBundle/Controller/DefaultController.php source code example, and find a small but **very** important difference against your src/HelloBundle/Controller/HelloController.php code.

PHPStorm parser shoud give you some hint or feedback about what's happening.

**Comment by aserratorta** [comment]
I overspent much time trying to resolve this shit and I only must have written <?php at the begining of the file!!!

Anyway...keep going!

**Comment by davidromani** [comment]
This kind of silly effort is really necessary. Now, you won't forget to write this tag anymore. :+1:
