### ISSUE TITLE
4.2.3.Creando la plantilla. (Twig or PHP language?)

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#6]
1)Which of both languages is better to use? I chose php.
2)I don't have exactly these folders in my SymfonyTraining: 
               src/HelloBundle/Resources/views/Hello/index.html.twig
Does it matter something?

**Comment by davidromani** [comment]
1) We love Twig, it is the best templating engine by far :smile: 

2) You must bind the controller with the view. To achieve this is very important to link your template view file.

<img width="826" alt="captura de pantalla 2015-08-17 a les 9 27 42" src="https://cloud.githubusercontent.com/assets/698779/9300096/d23fa5fa-44c2-11e5-8e2c-0cbf2d324157.png">

**Comment by aserratorta** [comment]
1)OK.
2)Of course, but i don't have src/HelloBundle/Resources/views/Hello/index.html.twig. I have src/HelloBundle/Resources/views/Default/index.html.twig. Must I change manually?

**Comment by davidromani** [comment]
Yes.

This is issue is related to code organization, by convention, we usually organize source code files with the same structure. Don't worry, you will learn it soon.

The most important thing is to know how (and why) the controller renders the response view template.
