### ISSUE TITLE
4.3.1. El directorio web

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#7]
Can it be useful?

Truco: Tener un controlador frontal significa que se utilizan URL diferentes y más flexibles que las de una aplicación PHP típica. Cuando se dispone de un controlador frontal, las URL se formatean de la siguiente manera:
http://localhost/app.php/hello/Ryan
El controlador frontal, app.php, se ejecuta y la URL interna: /hello/Ryan se dirige internamente según la configuración de enrutamiento.
Si además utilizas el módulo mod_rewrite de Apache, puedes forzar la ejecución del archivo app.php sin necesidad de incluirlo en la URL, por lo que así las URL son todavía más limpias:
http://localhost/hello/Ryan

**Comment by davidromani** [comment]
Don't worry about this for now. It's tied to Apache web server configuration in production (Internet) environment.
