### ISSUE TITLE
4.4.1. creando un bundle

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#8]
I can't execute this command:
php app/console generate:bundle --namespace=Prova/TestBundle

This is my terminal description:
anton@anton-System-Name:~$ php app/console generate:bundle --namespace=Prova/TestBundle
Could not open input file: app/console
anton@anton-System-Name:~$ cd Desenvolupament/SymfonyTraining/
anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$ php app/console generate:bundle --namespace=Prova/TestBundle
PHP Fatal error:  Class 'Prova\TestBundle\TestBundle' not found in /home/anton/Desenvolupament/SymfonyTraining/app/AppKernel.php on line 21
anton@anton-System-Name:~/Desenvolupament/SymfonyTraining$

**Comment by davidromani** [comment]
I think that you don't need a complex namespace. Try with:

```
php app/console generate:bundle --namespace=TestBundle
```

Your bundles root folder must be "src/", not "src/Prova/".

**Comment by aserratorta** [comment]
It doesn't work...

anton@anton-System-Name:~$ cd Desenvolupament/SymfonyTraining/src/
anton@anton-System-Name:~/Desenvolupament/SymfonyTraining/src$ php app/console generate:bundle --namespace=TestBundle
Could not open input file: app/console

**Comment by davidromani** [comment]
Because you are telling to the PHP command line interpreter (CLI) to execute the file "app/console" inside the "src" folder (why?).

You must launch it from "SymfonyTraining" base dir.
