### ISSUE TITLE
5.4. Clase base controlador

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/SymfonyTraining#9]
Let's talk about these tricks.
I can't find this folders.

**Comment by davidromani** [comment]
Wich ones? Be more specific, please.

**Comment by aserratorta** [comment]
This one, for exemple: 
**Symfony\Bundle\FrameworkBundle\Controller\Controller**
![screenshot - 180815 - 01 06 38](https://cloud.githubusercontent.com/assets/12971681/9318612/672140f2-4545-11e5-87b1-151ef3a2c1a2.png)

**Comment by davidromani** [comment]
All the "magic" is inside the vendors folder. Symfony itself is a third-party bundle (very cool feature :sunglasses:) 

And remember that all the external code that you need is managed by Composer (package manager)

<img width="400" alt="captura de pantalla 2015-08-18 a les 9 06 38" src="https://cloud.githubusercontent.com/assets/698779/9324302/40b9dcaa-4589-11e5-9ef4-a116bf75d07b.png">
